/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package person;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

class PersonTests {
    Person person = new Person("Jane","Doe");
    @Test
    void groupedAssertions () {
       // In a grouped assertion all assertions are executed, and all
       // failures will be reported together.
        assertAll ("person",
            () -> assertEquals ("Jane", Person.getFirstName ()) ,
            () -> assertEquals ("Doe", Person.getLastName ())
        );
    }

    @Test void dependentAssertions (){
   // Within a code block, if an assertion fails the
   // subsequent code in the same block will be skipped.
        assertAll ("properties",
        () -> { String firstName = Person.getFirstName ();
                assertNotNull(firstName);
                // Executed only if the previous assertion is valid.
                assertAll ("first name",
                    () -> assertTrue (firstName.startsWith ("J")),
                    () -> assertTrue (firstName.endsWith ("e"))
                    );},
        () -> {
            // Grouped assertion, so processed independently
            // of results of first name assertions.
                String lastName = Person.getLastName ();
                assertNotNull (lastName) ;
            // Executed only if the previous assertion is valid.
            assertAll ("last name",
                () -> assertTrue (lastName.startsWith ("D")),
                () -> assertTrue (lastName.endsWith ("e")));
            }
    );
}}



